// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHEUzu14KG252mAwIt_vf-eC60iTEpZ48',
    appId: '1:234919338747:web:bb031520f3603213d2465e',
    messagingSenderId: '234919338747',
    projectId: 'tideup-7e8c9',
    authDomain: 'tideup-7e8c9.firebaseapp.com',
    storageBucket: 'tideup-7e8c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxMsLl_flGcLQsQCzCU4cqbppxbAauUOU',
    appId: '1:234919338747:android:5bb527e66b59f8dcd2465e',
    messagingSenderId: '234919338747',
    projectId: 'tideup-7e8c9',
    storageBucket: 'tideup-7e8c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACuSsKgzEY1ESPt2JKoAHJ8VTDR9TzGIY',
    appId: '1:234919338747:ios:9ea13b2b1e0df946d2465e',
    messagingSenderId: '234919338747',
    projectId: 'tideup-7e8c9',
    storageBucket: 'tideup-7e8c9.firebasestorage.app',
    androidClientId: '234919338747-s7pkr6j8hljv1gh2a1i3t95u2fclcb1u.apps.googleusercontent.com',
    iosClientId: '234919338747-tk6kmr6qbvvcldem8md2sitdfju26dup.apps.googleusercontent.com',
    iosBundleId: 'com.tideup.sudarshan.tideup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACuSsKgzEY1ESPt2JKoAHJ8VTDR9TzGIY',
    appId: '1:234919338747:ios:9ea13b2b1e0df946d2465e',
    messagingSenderId: '234919338747',
    projectId: 'tideup-7e8c9',
    storageBucket: 'tideup-7e8c9.firebasestorage.app',
    androidClientId: '234919338747-s7pkr6j8hljv1gh2a1i3t95u2fclcb1u.apps.googleusercontent.com',
    iosClientId: '234919338747-tk6kmr6qbvvcldem8md2sitdfju26dup.apps.googleusercontent.com',
    iosBundleId: 'com.tideup.sudarshan.tideup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHEUzu14KG252mAwIt_vf-eC60iTEpZ48',
    appId: '1:234919338747:web:60c4c0ed8b9b11c9d2465e',
    messagingSenderId: '234919338747',
    projectId: 'tideup-7e8c9',
    authDomain: 'tideup-7e8c9.firebaseapp.com',
    storageBucket: 'tideup-7e8c9.firebasestorage.app',
  );

}